---
- name: Aruba Cihaz Versiyon Bilgisi Toplama
  hosts: all
  gather_facts: no

  tasks:
    - name: show version Komutunu Calistir (RAW Modu)
      ansible.builtin.raw: "show version"   # <-- JOKER MODÜL
      register: komut_cikti

    - name: Cihazdan Gelen Ham Ciktiyi Goster
      debug:
        msg: "{{ komut_cikti.stdout_lines }}"
