---
- name: Aruba Cihaz Versiyon Bilgisi Toplama
  hosts: all
  gather_facts: no

  tasks:
    - name: show version Komutunu Calistir
      arubanetworks.aos_switch.arubaoss_command:   # <-- BURASI DOĞRU, KALSIN
        commands: show version
      register: komut_cikti

    - name: Cihazdan Gelen Ham Ciktiyi Goster
      debug:
        msg: "{{ komut_cikti.stdout_lines }}"
