---
- name: Aruba Versiyon Kontrol (Zorlama Modu)
  hosts: all
  gather_facts: no
  
  # BURASI KRITİK: AWX'teki ayarları ezmek için buraya yazıyoruz
  vars:
    ansible_connection: ssh          # Network modülünü devre dışı bırak
    ansible_network_os: null         # Eski 'arubaoss' tanımını iptal et
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  tasks:
    # 1. Hangi ayarlarla çalıştığımızı görelim (Debug)
    - name: Degisken Kontrolu
      debug:
        msg: "Baglanti Tipi: {{ ansible_connection }}"

    # 2. RAW (Saf SSH) Modu ile komut gönder
    - name: show version Komutunu Calistir
      ansible.builtin.raw: show version
      register: komut_cikti

    # 3. Sonucu Ekrana Bas
    - name: Ciktiyi Goster
      debug:
        msg: "{{ komut_cikti.stdout_lines | default(komut_cikti.stdout) }}"
