---
- name: Aruba Cihaz Versiyon Bilgisi Toplama
  hosts: all
  gather_facts: no  # Sadece istedigimiz komutu kosacagiz, vakit kaybetmeyelim.

  tasks:
    # 1. ADIM: Komutu Cihaza Gönder
    - name: show version Komutunu Calistir
      community.network.aruba_command:
        commands: show version
      register: komut_cikti   # SONUCU HAFIZAYA KAYDET (Variable)

    # 2. ADIM: Hafizadaki Sonucu Ekrana Yazdir
    - name: Cihazdan Gelen Ham Ciktiyi Goster
      debug:
        msg: "{{ komut_cikti.stdout_lines[0] }}"
